language: rust

env:
  global:
    - secure: O14lnD45q3oyuMtKU7Jfy1e+LSs91UZPnNuTPT9IZNoHPgJM77mdK1bwu5SqSXpmDEaq3uQBBhIKEKxiOgogiRAGcALnjSLIe02qrw8kR4hhB7IsuCsfJA3rgnH5NrSxV2ja5wHUkTtYORIB30GX/SU4qNw8C+HeAcXDaxPRNJYuIkE41jW121PDgheS7Ti49ui5JOKss/FdpI8Ii5xXvNf9Z60MSJKPsM8yaj+RiqDccXrFuyppVE/Ezn95gdJh1Sr7BUaP521FOhOYl4bvMEV0pHHMwaPD0b2Ku0yJ+GrZiZ2YqTmsNiaa4hN2AAv38w46KfhQuvJg173cEGf6hCrrF+IOQvmGG977xSO7tci2l5idjIZ1xtXsLQ9Yp49DBxd1s2I20j+fHmCImH1cV4+hEnMTQLITzemS3MkHIxbEgcMyssjZD7FASNU1C3fbeeHEG3JPM/hHj0mlGlhv7T54gL5Q7Qggnj+xsE44yU18bP0K/G48QBLeXDSfZzeaCbrif9bALAVnUMhRMSuW9EfOHcu7juaBAj5mPxWfN4CoQgqBFPh+V+q6+WViV0/5djoKlrOy323hNTg+CXIqWn9RYIbxbyRMGXIU6Z78Sr6Yls+8tK1cpdXOzQ6CMeUJh2H264hFMM1ZGvlQ+VYqRYMCViuVW4Aofuqr1zfsnz0=
    - secure: xm+WIGYVoYvjAlWOaoli0YZ4LMFBKd7pG0qno4zrDMGrz1AwLRK6dce0+ROvIdEcuOror2j4wryYgDRMLYgxzhXeMMVFkxZuB1MmeC8VHirf0jNHNNihWwnEyTDGtj5VXijD/ipo4jiskBZEsg/oW97iFUudjl/rNT2R0Gy420QgGV4p3m9jTjBBL6giIQUNK0g+5aIkCfb4U/4gcpFA5nZJgyfQtnKKmVnEPl26vbU+Ui7F/wqTK0a7AJT3RCaEddtu7E5DKNnk4/45e4//LKNEE8I2KGqWlqWXqFYs+Cno1trDOcKm0yiTIquvbZsrOuH7wN1il4qVcsdgQLps2kFahpJyQJbJJViBkbqnlwRJDnxtszbrxSGW6HiVMSSd8AOthwJd3n7lMkBDwrwG9Dx7MiNY/NIdRxufEuoOw/6tj31oBJhM1s+/Fhjzlz0j5R5spTtcaNg6Q0Gi+F283jjwvobIzvUUKKSt4I1UZLTQNSzxrWTJZ4kJBG1JiTxH7BwHMtxhiaZn5ajk5HfVXScmBknZIovsylj5UXp1d5IhXUNq4jTXTdybOurhQ1XLVz/hw64oOIQkuftaNHuQMe3oB69aWLWpS6+r3k1ZCT/WODbS3xlhp/MXO3WLD4WY1OWJ522t/YOUQX3j72bZADlQOcU/OWQ5LWNC3XGibrk=

cache: cargo

install:
  - rustc -vV
  - cargo -vV

jobs:
  allow_failures:
    - rust: nightly
      stage: build

  include:
#    - name: Clippy
#      stage: check
#      rust: stable
#      before_script: rustup component add clippy
#      script: make lint
#
#    - name: rustfmt
#      stage: check
#      rust: nightly
#      cache: false
#      before_script: rustup component add rustfmt
#      script: make fmt check=yes
#
#    - name: medea-jason (stable)
#      stage: build
#      rust: stable
#      before_script:
#        - rm -f /home/travis/.cargo/bin/wasm-pack
#        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
#      script:
#        - make release.npm crate=medea-jason publish=no

    - name: medea docker (stable)
      stage: build
      rust: stable
      addons:
        apt:
          packages:
            - pass
      script:
#        - make docker.build.medea debug=no TAG=${TRAVIS_BUILD_ID}
        - ./ci/docker-pass.sh
        - echo "$QUAYIO_PASS" | docker login quay.io -u "$QUAYIO_USER" --password-stdin
#        - make docker.tar TAGS=${TRAVIS_BUILD_ID}
#        - ls .cache/docker/

#    - name: medea (beta)
#      stage: build
#      rust: beta
#      script: make build.medea
#
#    - name: medea (nightly)
#      stage: build
#      rust: nightly
#      script: make build.medea
#
#    - name: unit (stable)
#      stage: test
#      rust: stable
#      script: make test.unit crate=@all
#
#    - name: e2e signalling (stable)
#      stage: test
#      rust: stable
#      script:
#        - ls .cache/
#        - make docker.untar TAGS=${TRAVIS_BUILD_ID}
#        - make test.e2e dockerized=yes logs=yes TAG=${TRAVIS_BUILD_ID}

    - name: crates.io
      stage: release
      if: (tag IS present) AND (tag =~ ^medea[a-z-]*-[0-9]+\.[0-9]+\.[0-9]+)
      cache: false
      before_script:
        - export MEDEA_CRATE_NAME=$(echo $TRAVIS_TAG \
                        | sed -E "s/^(medea[a-z-]*)-[0-9]+\.[0-9]+\.[0-9]+/\1/")
      script:
        - echo "Releasing $MEDEA_CRATE_NAME to crates.io..."
      deploy:
        provider: script
        skip_cleanup: true
        script: make release.crates crate=$MEDEA_CRATE_NAME publish=yes
        on:
          tags: true

    - name: NPM
      stage: release
      if: (tag IS present) AND (tag =~ ^medea-jason-[0-9]+\.[0-9]+\.[0-9]+)
      cache: false
      before_script:
        - export MEDEA_CRATE_NAME=$(echo $TRAVIS_TAG \
                        | sed -E "s/^(medea[a-z-]*)-[0-9]+\.[0-9]+\.[0-9]+/\1/")
      script:
        - echo "Releasing $MEDEA_CRATE_NAME to NPM..."
      before_deploy:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      deploy:
        provider: script
        skip_cleanup: true
        script: make release.npm crate=$MEDEA_CRATE_NAME publish=yes
        on:
          tags: true

    - name: GitHub
      stage: release
      if: (tag IS present) AND (tag =~ ^medea[a-z-]*-[0-9]+\.[0-9]+\.[0-9]+)
      cache: false
      before_script:
        - export MEDEA_CRATE_NAME=$(echo $TRAVIS_TAG \
                        | sed -E "s/^(medea[a-z-]*)-[0-9]+\.[0-9]+\.[0-9]+/\1/")
      script:
        - echo "Releasing $MEDEA_CRATE_NAME to GitHub..."
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: $GH_TOKEN
        name: $TRAVIS_TAG
        on:
          tags: true

stages:
  - name: check
    if: (branch = master AND type != pull_request) OR commit_message =~ /.*\[run ci\]/
  - name: build
    if: (branch = master AND type != pull_request) OR commit_message =~ /.*\[run ci\]/
  - name: test
    if: (branch = master AND type != pull_request) OR commit_message =~ /.*\[run ci\]/
  - name: tests
    if: (branch = master AND type != pull_request) OR commit_message =~ /.*\[run ci\]/

notifications:
  email:
    on_success: never
    on_failure: always
