language: rust

services:
  - docker

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly

    - rust: stable
      name: clippy
      before_script:
        - rustup component add clippy
      script:
        - cargo clippy

    - rust: nightly
      name: rustfmt
      before_script:
        - rustup component add rustfmt
      script:
        make fmt check=yes

  allow_failures:
    - rust: nightly

install:
  - rustc -vV
  - cargo -vV

script:
  - cargo build
  - make test.unit

notifications:
  email:
    on_success: never
    on_failure: always
