language: rust

services:
  - docker

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

jobs:
  allow_failures:
    - rust: nightly
      stage: build

  include:
    - stage: lints
      rust: stable
      name: "Clippy"
      before_script: rustup component add clippy
      script: make lint

    - stage: formatting
      rust: nightly
      name: "Rustfmt"
      before_script: rustup component add rustfmt
      script: make fmt check=yes

    - stage: build
      rust: stable
      name: "Build jason (Rust stable)"
      before_script:
        - rm -f /home/travis/.cargo/bin/wasm-pack
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      script:
        - wasm-pack build -t web jason

    - stage: build
      rust: stable
      name: "Build medea (Rust stable)"
      script: cargo build

    - stage: build
      rust: beta
      name: "Build medea (Rust beta)"
      script: cargo build

    - stage: build
      rust: nightly
      name: "Build medea (Rust nightly)"
      script: cargo build

    - stage: tests
      rust: stable
      name: "Unit tests (Rust stable)"
      script: make test.unit

    - stage: tests
      rust: stable
      name: "E2E tests (Rust stable)"
      script: make test.e2e


install:
  - rustc -vV
  - cargo -vV
  - rustup update stable

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

deploy:
  - provider: script
    script: make release.crates.medea
    on:
      tags: true
      branch: master
      condition: $TRAVIS_TAG =~ ^medea-[0-9]+\.[0-9]+\.[0-9]+

  - provider: script
    script: make release.jason
    on:
      tags: true
      branch: master
      condition: $TRAVIS_TAG =~ ^medea-jason-[0-9]+\.[0-9]+\.[0-9]+

  - provider: script
    script: make release.crates.medea-client-api-proto
    on:
      tags: true
      branch: master
      condition: $TRAVIS_TAG =~ ^medea-client-api-proto-[0-9]+\.[0-9]+\.[0-9]+

  - provider: script
    script: make release.crates.medea-macro
    on:
      tags: true
      branch: master
      condition: $TRAVIS_TAG =~ ^medea-macro-[0-9]+\.[0-9]+\.[0-9]+

  - provider: releases
    api_key: $GH_TOKEN
    on:
      tags: true
      branch: master

notifications:
  email:
    on_success: never
    on_failure: always
