language: rust

jobs:
  allow_failures:
    - rust: nightly
      stage: build

  include:
    - stage: lints
      rust: nightly
      name: "Clippy"
      before_script: rustup component add clippy
      script: make lint

    - stage: formatting
      rust: nightly
      name: "Rustfmt"
      before_script: rustup component add rustfmt
      script: make fmt check=yes

    - stage: build
      rust: stable
      name: "Build medea (Rust stable)"
      script: cargo build

    - stage: build
      rust: beta
      name: "Build medea (Rust beta)"
      script: cargo build

    - stage: build
      rust: nightly
      name: "Build medea (Rust nightly)"
      script: cargo build

    - stage: tests
      rust: stable
      name: "Unit tests (Rust stable)"
      script: make test.unit


install:
  - rustc -vV
  - cargo -vV

notifications:
  email:
    on_success: never
    on_failure: never # TODO: set to always when .travis.yml will be debugged
