language: rust

services:
  - docker

cache:
  cargo: true

install:
  - PROTOBUF_VERSION=3.3.0
  - PROTOC_FILENAME=protoc-${PROTOBUF_VERSION}-linux-x86_64.zip
  - pushd /home/travis
  - wget https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/${PROTOC_FILENAME}
  - unzip ${PROTOC_FILENAME}
  - bin/protoc --version
  - popd

jobs:
  allow_failures:
    - rust: nightly
      stage: build

  include:
    - name: Clippy
      stage: check
      rust: stable
      before_script: rustup component add clippy
      script: make lint

    - name: rustfmt
      stage: check
      rust: nightly
      before_script: rustup component add rustfmt
      script: make fmt check=yes build=yes

    - name: medea-jason (stable)
      stage: build
      rust: stable
      before_script:
        - rm -f /home/travis/.cargo/bin/wasm-pack
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      script:
        - wasm-pack build -t web jason

    - name: medea (stable)
      stage: build
      rust: stable
      before_script:
        - sccache --version || cargo install sccache && sccache --version
      script: env RUSTC_WRAPPER=sccache cargo build

    - name: medea (beta)
      stage: build
      rust: beta
      before_script:
        - sccache --version || cargo install sccache && sccache --version
      script: env RUSTC_WRAPPER=sccache cargo build

    - name: medea (nightly)
      stage: build
      rust: nightly
      before_script:
        - sccache --version || cargo install sccache && sccache --version
      script: env RUSTC_WRAPPER=sccache cargo build

    - name: unit (stable)
      stage: tests
      rust: stable
      script: make test.unit

    - name: signalling e2e (stable)
      stage: tests
      rust: stable
      before_script:
        - mkdir .cache
      script: make test.e2e.signalling

    - name: e2e (stable, firefox)
      stage: tests
      rust: stable
      before_script:
        - mkdir .cache
      script: make test.e2e.firefox

    - name: e2e (stable, chrome)
      stage: tests
      rust: stable
      before_script:
        - mkdir .cache
      script: make test.e2e.chrome

notifications:
  email:
    on_success: never
    on_failure: always
