[package]
name = "medea"
version = "0.1.0"
description = "Medea media server"
homepage = "https://github.com/instrumentisto/medea"
documentation = "https://github.com/instrumentisto/medea/tree/master/docs/rfc"
readme = "README.md"
edition = "2018"

[dependencies]
chrono = "0.4.6"
log = "0.4.6"
slog = { version = "2.4.1", features = ["max_level_trace", "release_max_level_warn"] }
slog-async = "2.3.0"
slog-json = "2.3.0"
slog-scope = "4.1.1"
slog-stdlog = "3.0.4-pre"
slog-stream = "1.2.1"
slog-term = "2.4.0"
