[package]
name = "medea"
version = "0.1.0"
edition = "2018"
description = "Medea media server"
authors = ["Instrumentisto Team <developer@instrumentisto.com>"]
homepage = "https://github.com/instrumentisto/medea"
# documentation = "https://docs.rs/medea"
readme = "README.md"
repository = "https://github.com/instrumentisto/medea"

[dependencies]
config = "0.9"
chrono = "0.4"
dotenv = "0.13"
failure = "0.1"
hashbrown = "0.1"
lazy_static = "1.2"
regex = "1"
serde = "1"
serde_derive = "1"
slog = { version = "2.4", features = ["max_level_debug", "release_max_level_warn"] }
slog-async = "2.3"
slog-json = "2.3"
slog-scope = "4.1"
toml = "0.4"
