[package]
name = "medea"
version = "0.1.0-dev"
edition = "2018"
description = "Medea media server"
authors = ["Instrumentisto Team <developer@instrumentisto.com>"]
homepage = "https://github.com/instrumentisto/medea"
# documentation = "https://docs.rs/medea"
readme = "README.md"
repository = "https://github.com/instrumentisto/medea"

[workspace]
members = [
    "crates/medea-macro",
    "jason",
    "proto/client-api",
]

[profile.release]
lto = "thin"

[dependencies]
actix = "0.8"
actix-codec = "0.1"
actix-http = "0.2"
actix-http-test = "0.2"
actix-web = "1.0"
actix-web-actors = "1.0"
# TODO: use version from crates.io when commit
# https://github.com/actix/actix-web/commit/ff724e239db50210a9913de6e214be214f41befa#diff-c39fd968c2b6beb9a6960dd533618bcbR41
# will be released in crates.io.
awc = { git = "https://github.com/actix/actix-web" }
bb8 = "0.3"
bb8-redis = "0.3"
config = "0.9"
chrono = "0.4"
dotenv = "0.13"
failure = "0.1"
futures = "0.1"
hashbrown = "0.1"
humantime = "1.2"
macro-attr = "0.2"
medea-client-api-proto = { path = "proto/client-api", features = ["medea"] }
medea-macro = { path = "crates/medea-macro" }
newtype_derive = "0.1"
rand = "0.6"
redis = "0.10"
rust-crypto = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
slog = "2.4"
slog-envlogger = "2.1"
slog-stdlog = "3.0"
slog-async = "2.3"
slog-json = "2.3"
slog-scope = "4.1"
smart-default = "0.5"
tokio = "0.1"
toml = "0.4"
[dependencies.serde-humantime]
    git = "https://github.com/tailhook/serde-humantime"
    branch = "serde_wrapper"

[dev-dependencies]
serial_test = "0.2"
serial_test_derive = "0.2"
