[package]
name = "medea"
version = "0.1.0"
description = "Medea media server"
homepage = "https://github.com/instrumentisto/medea"
documentation = "https://github.com/instrumentisto/medea/tree/master/docs/rfc"
readme = "README.md"
edition = "2018"

[dependencies]
actix = "0.7"
chrono = "0.4"
failure = "0.1"
futures = "0.1"
im = "12.3"
log = "0.4"
slog = { version = "2.4", features = ["max_level_info", "release_max_level_warn"] }
slog-async = "2.3"
slog-json = "2.3"
slog-scope = "4.1"
tokio = "0.1"
