[package]
name = "medea"
version = "0.1.0"
description = "Medea media server"
homepage = "https://github.com/instrumentisto/medea"
documentation = "https://github.com/instrumentisto/medea/tree/master/docs/rfc"
readme = "README.md"
edition = "2018"

[dependencies]
actix = "0.7"
actix-web = "0.7"
chrono = "0.4"
dotenv = "0.13"
failure = "0.1"
futures = "0.1"
im = "12.3"
slog = "2.4"
slog-envlogger = "2.1"
slog-stdlog = "3.0"
slog-async = "2.3"
slog-json = "2.3"
slog-scope = "4.1"
tokio = "0.1"
