version: "2"

services:
  medea:
    container_name: ${COMPOSE_PROJECT_NAME}-backend
    image: ${COMPOSE_IMAGE_NAME}:${COMPOSE_IMAGE_VER}
    ports:
      - "8080:8080"
    volumes:
      - ${MEDEA_SERVER_STATIC_SPECS_PATH}:/specs
      - ./config.toml:/config.toml
    network_mode: "host"
    environment:
      RUST_LOG: ${RUST_LOG}
      MEDEA_CONF: "config.toml"
      MEDEA_SERVER.STATIC_SPECS_PATH: /specs
