version: "2"

services:
  medea:
    container_name: ${COMPOSE_PROJECT_NAME}-backend
    image: ${COMPOSE_IMAGE_NAME}:${COMPOSE_IMAGE_VER}
    ports:
      - "8080:8080"
    environment:
      RUST_LOG: ${RUST_LOG}
    volumes:
      - ./dev/config.toml:/config.toml:ro
      - ./dev/specs:/specs:ro
    network_mode: host
