apiVersion: v1
entries:
  medea-demo:
  - apiVersion: v1
    appVersion: 0.1.0
    created: "2019-11-07T15:14:43.519513+02:00"
    digest: e4bdbcd139aa1e66f2a27bd22f70143c8b0af625e0aefc1cd3b4530f41f2e0a0
    name: medea-demo
    urls:
    - https://instrumentisto.github.io/medea/charts/medea-demo-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    appVersion: 0.1.0
    created: "2019-11-07T15:14:43.51886+02:00"
    digest: ac4e5cee69a8c49cd42b3b96875de82595bf25a5f32a849cafbc006518e5fa2f
    name: medea-demo
    urls:
    - https://instrumentisto.github.io/medea/charts/medea-demo-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    appVersion: 0.1.0
    created: "2019-11-07T15:14:43.51636+02:00"
    digest: 309cdd8aa637c7385122b1d323dd73a3a26e10d0f8bfaefc4ea9e0b3b127610b
    name: medea-demo
    urls:
    - https://instrumentisto.github.io/medea/charts/medea-demo-0.1.0.tgz
    version: 0.1.0
generated: "2019-11-07T15:14:43.515246+02:00"
