version: "2"

services:
  web-client:
    container_name: demo-web-client
    image: instrumentisto/medea-demo:dev
    ports:
      - "80:80"        # web-client http
      - "6379:6379"    # coturn redis
      - "8080:8080"    # medea ws
      - "9050:9050"
      - "50051:50051"
    volumes:
      - ./chart/medea-demo/conf/nginx.vh.conf:/etc/nginx/conf.d/default.conf
  medea:
    container_name: demo-medea
    image: instrumentisto/medea:dev
    depends_on: ["coturn-db"]
    environment:
      RUST_LOG: "DEBUG"
    network_mode: service:web-client
  control-api-mock:
    container_name: demo-control-api-mock
    image: instrumentisto/medea-control-api-mock:dev
    environment:
      RUST_LOG: "DEBUG"
    depends_on:
      - coturn-db
    network_mode: service:web-client
  coturn:
    container_name: demo-coturn
    image: instrumentisto/coturn:4.5
    depends_on: ["coturn-db"]
    command:
      - --log-file=stdout
      #- --verbose
    volumes:
      - ../../dev/coturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
      - ../../.cache/coturn/data:/var/lib/coturn
    network_mode: host
  coturn-db:
    container_name: demo-coturn-db
    image: redis:alpine
    command: ["redis-server", "/etc/redis.conf"]
    volumes:
      - ../../dev/coturn/redis.conf:/etc/redis.conf:ro
    network_mode: service:web-client
